development: &default
  app_key: "hcpgnx0ljsxl7hc"
  app_secret: "vys1ig1ygi9amv7"
  access_token: "9um0svf2ttq55649"
  access_token_secret: "fvkib41ysrt34i4"
  user_id: "161536391"
  access_type: "app_folder"
test:
  <<: *default
production:
  app_key: <%= ENV["DROPBOX_APP_KEY"] %>
  app_secret: <%= ENV["DROPBOX_APP_SECRET"] %>
  access_token: <%= ENV["DROPBOX_ACCESS_TOKEN"] %>
  access_token_secret: <%= ENV["DROPBOX_ACCESS_TOKEN_SECRET"] %>
  user_id: <%= ENV["DROPBOX_USER_ID"] %>
  access_type: <%= ENV["DROPBOX_ACCESS_TYPE"] %>