development: &default
  app_key: "hcpgnx0ljsxl7hc"
  app_secret: "vys1ig1ygi9amv7"
  access_token: "9um0svf2ttq55649"
  access_token_secret: "fvkib41ysrt34i4"
  user_id: "161536391"
  access_type: "app_folder"
test:
  <<: *default
production:
  <<: *default